DIVIDEND_LIST = [

    "AADI", "AALI", "ABMM", "ACES", "ACRO", "ADMF", "ADMR", "ADRO", "AKRA", "AMAG", 
    "AMAR", "AMIN", "AMOR", "AMRT", "ANTM", "ARCI", "ARNA", "ASDM", "ASGR", "ASII", 
    "ASRI", "ASSA", "AUTO", "AVIA", "AXIO", "BALI", "BAYU", "BBCA", "BBNI", "BBRI", 
    "BBTN", "BDMN", "BFIN", "BIRD", "BISI", "BJBR", "BJTM", "BMRI", "BNGA", "BOBA", 
    "BPFI", "BREN", "BRIS", "BRPT", "BSDE", "BSSR", "BTPS", "BUAH", "BUDI", "BYAN", 
    "CEKA", "CFIN", "CINT", "CITA", "CLEO", "CLPI", "CMRY", "CNMA", "CTBN", "CTRA", 
    "CUAN", "DAAZ", "DGWG", "DKFT", "DLTA", "DMAS", "DOID", "DRMA", "DSNG", "DVLA", 
    "EAST", "EKAD", "ELSA", "EMTK", "EPMT", "ERAA", "ESSA", "EXCL", "FWCT", "GEMA", 
    "GEMS", "GGRM", "GHON", "GJTL", "GLVA", "GOOD", "GPRA", "GUNA", "HAIS", "HEXA", 
    "HMSP", "HOKI", "HRUM", "ICBP", "IFII", "IKBI", "IMAS", "INCI", "INDF", "INDY", 
    "INTP", "IPCM", "ISAT", "ISSP", "ITMG", "JAYA", "JKON", "JSMR", "KBLI", "KBLM", 
    "KBLV", "KDSI", "KEEN", "KKGI", "KLBF", "KMDS", "LPIN", "LPKR", "LPPF", "LSIP", 
    "LTLS", "MAHA", "MAIN", "MAPA", "MAPI", "MARK", "MBAP", "MCOL", "MDKA", "MDKI", 
    "MDLA", "MEDC", "MEGA", "MERK", "MKPI", "MLBI", "MMLP", "MPMX", "MSTI", "MTDL", 
    "MTEL", "MYOH", "MYOR", "NCKL", "NICL", "NISP", "NRCA", "OBAT", "PANR", "PANS", 
    "PBID", "PBSA", "PGAS", "PGEO", "PJAA", "PNBN", "PNGO", "POWR", "PPGL", "PRDA", 
    "PSGO", "PTBA", "PTPS", "PTRO", "PWON", "RAJA", "RALS", "RMKE", "ROTI", "SAMF", 
    "SBMA", "SCCO", "SCMA", "SDRA", "SGRO", "SICO", "SIDO", "SKLT", "SKRN", "SMAR", 
    "SMDR", "SMGR", "SMRA", "SMSM", "SPTO", "SRTG", "SSMS", "STAA", "SUNI", "TAPG", 
    "TBMS", "TCID", "TEBE", "TGKA", "TIFA", "TINS", "TLDN", "TLKM", "TMAS", "TOBA", 
    "TOTL", "TOTO", "TOWR", "TPIA", "TPMA", "TRIS", "TRUS", "TSPC", "TUGU", "UCID", 
    "ULTJ", "UNIC", "UNTD", "UNTR", "UNVR", "WEHA", "WIIM", "WOMF", "YUPI", 
]
