SAHAM_SECTOR = {

    # ===== BANK & FINANCE =====
    "BBCA": "BANK",
    "BBRI": "BANK",
    "BMRI": "BANK",
    "BBNI": "BANK",
    "ARTO": "BANK",
    "BRIS": "BANK",
    "BTPS": "BANK",
    "BNGA": "BANK",
    "BBTN": "BANK",
    "NISP": "BANK",
    "INPC": "BANK",

    "TRIM": "FINANCE",
    "AKSI": "FINANCE",

    # ===== TELECOM / TOWER =====
    "TLKM": "TELECOM",
    "EXCL": "TELECOM",
    "ISAT": "TELECOM",
    "FREN": "TELECOM",
    "IBST": "TELECOM",

    "MTEL": "INFRA",

    # ===== ENERGY & MINING =====
    "ADRO": "MINING",
    "ITMG": "MINING",
    "PTBA": "MINING",
    "ANTM": "MINING",
    "MDKA": "MINING",
    "TINS": "MINING",
    "HRUM": "MINING",
    "INDY": "MINING",
    "DOID": "MINING",
    "BUMI": "MINING",
    "MBAP": "MINING",
    "BSSR": "MINING",
    "GEMS": "MINING",
    "ARCI": "MINING",
    "NICL": "MINING",
    "NCKL": "MINING",
    "PSAB": "MINING",
    "SMRU": "MINING",
    "ABMM": "MINING",
    "KKGI": "MINING",
    "POLU": "MINING",

    "ELSA": "ENERGY",
    "MEDC": "ENERGY",
    "AKRA": "ENERGY",
    "RAJA": "ENERGY",
    "BRPT": "ENERGY",
    "PTRO": "ENERGY",
    "TOBA": "ENERGY",
    "RATU": "ENERGY",
    "WOWS": "ENERGY",
    "HELI": "ENERGY",
    "BREN": "ENERGY",
    "SUGI": "ENERGY",
    "GOLD": "ENERGY",

    # ===== CONSUMER =====
    "UNVR": "CONSUMER",
    "ICBP": "CONSUMER",
    "INDF": "CONSUMER",
    "MYOR": "CONSUMER",
    "KLBF": "CONSUMER",
    "ULTJ": "CONSUMER",
    "CLEO": "CONSUMER",
    "KINO": "CONSUMER",
    "ZATA": "CONSUMER",
    "COCO": "CONSUMER",
    "BUAH": "CONSUMER",
    "SIMA": "CONSUMER",
    "CINT": "CONSUMER",

    # ===== RETAIL =====
    "AMRT": "RETAIL",
    "RALS": "RETAIL",
    "ACES": "RETAIL",
    "ERAA": "RETAIL",
    "MAPI": "RETAIL",
    "MAPA": "RETAIL",
    "MPPA": "RETAIL",
    "FAST": "RETAIL",
    "DEPO": "RETAIL",

    # ===== AGRI =====
    "SMAR": "AGRI",

    # ===== PROPERTY =====
    "CTRA": "PROPERTY",
    "BSDE": "PROPERTY",
    "PWON": "PROPERTY",
    "ASRI": "PROPERTY",
    "SMRA": "PROPERTY",
    "BKSL": "PROPERTY",
    "DMAS": "PROPERTY",
    "APLN": "PROPERTY",
    "DILD": "PROPERTY",
    "LPKR": "PROPERTY",
    "PPRO": "PROPERTY",
    "CITY": "PROPERTY",
    "GPRA": "PROPERTY",
    "EMDE": "PROPERTY",
    "PLAN": "PROPERTY",
    "MMLP": "PROPERTY",
    "MTSM": "PROPERTY",
    "MPRO": "PROPERTY",
    "PURI": "PROPERTY",
    "GAMA": "PROPERTY",
    "REAL": "PROPERTY",
    "BKDP": "PROPERTY",

    # ===== INFRA =====
    "JSMR": "INFRA",
    "CSIS": "INFRA",
    "KBLV": "INFRA",
    "FWCT": "INFRA",
    "VKTR": "INFRA",
    "OPMS": "INFRA",

    # ===== TRANSPORT / LOGISTIC =====
    "ASSA": "TRANSPORT",
    "WEHA": "TRANSPORT",
    "LEAD": "TRANSPORT",
    "BIRD": "TRANSPORT",
    "PSSI": "TRANSPORT",
    "JARR": "TRANSPORT",
    "RMKE": "TRANSPORT",
    "HITS": "TRANSPORT",
    "MEJA": "TRANSPORT",
    "LAJU": "TRANSPORT",
    "GTSI": "TRANSPORT",

    # ===== TECH / DIGITAL =====
    "GOTO": "TECH",
    "BUKA": "TECH",
    "DCII": "TECH",
    "MCAS": "TECH",
    "WIFI": "TECH",
    "EDGE": "TECH",
    "ENVY": "TECH",
    "COIN": "TECH",
    "DIVA": "TECH",
    "MORA": "TECH",
    "MMIX": "TECH",
    "DGNS": "TECH",
    "TFAS": "TECH",
    "SOTS": "TECH",
    "NETV": "TECH",
    "YELO": "TECH",
    "UANG": "TECH",

    # ===== MANUFACTURING / INDUSTRIAL =====
    "ASII": "MANUFACTURING",
    "GJTL": "MANUFACTURING",
    "POLY": "MANUFACTURING",
    "SMGR": "MANUFACTURING",
    "INTP": "MANUFACTURING",
    "IKBI": "MANUFACTURING",
    "KRYA": "MANUFACTURING",
    "ALKA": "MANUFACTURING",
    "INAI": "MANUFACTURING",
    "LMPI": "MANUFACTURING",
    "PACK": "MANUFACTURING",
    "TRJA": "MANUFACTURING",

    # ===== AUTO =====
    "AUTO": "AUTO",
    "IMAS": "AUTO",

    # ===== HOLDING / INVESTMENT =====
    "TPIA": "INDUSTRIAL",
    "CUAN": "HOLDING",
    "CDIA": "HOLDING",
    "ALII": "HOLDING",
    "MTRA": "HOLDING",

    # ===== HEALTH =====
    "CARE": "HEALTH",

    # ===== MEDIA =====
    "STAR": "MEDIA",

    # ===== OTHERS / SPECULATIVE =====
    "SUPA": "SPECULATIVE",
    "RLCO": "SPECULATIVE",
    "PANI": "SPECULATIVE",
    "SOCI": "SPECULATIVE",
    "MARK": "SPECULATIVE",
    "AGII": "SPECULATIVE",
    "TAYS": "SPECULATIVE",
    "PSKT": "SPECULATIVE",
    "TOOL": "SPECULATIVE",
    "NUSA": "SPECULATIVE",
    "SMMT": "SPECULATIVE",
    "CBMF": "SPECULATIVE",
    "ESTA": "SPECULATIVE",
    "CASH": "SPECULATIVE",
}