SAHAM_SECTOR = {

    # ===== BANK & FINANCE =====
    "BBCA": "BANK",
    "BBRI": "BANK",
    "BMRI": "BANK",
    "BBNI": "BANK",
    "ARTO": "BANK",
    "BRIS": "BANK",
    "BTPS": "BANK",
    "BNGA": "BANK",
    "BBTN": "BANK",
    "NISP": "BANK",
    "TRIM": "FINANCE",

    # ===== TELECOM =====
    "TLKM": "TELECOM",
    "EXCL": "TELECOM",
    "ISAT": "TELECOM",
    "FREN": "TELECOM",
    "MTEL": "INFRA",

    # ===== ENERGY & MINING =====
    "ADRO": "MINING",
    "ITMG": "MINING",
    "PTBA": "MINING",
    "ANTM": "MINING",
    "MDKA": "MINING",
    "TINS": "MINING",
    "HRUM": "MINING",
    "INDY": "MINING",
    "DOID": "MINING",
    "BUMI": "MINING",
    "ELSA": "ENERGY",
    "MEDC": "ENERGY",
    "AKRA": "ENERGY",
    "RAJA": "ENERGY",
    "BRPT": "ENERGY",

    # ===== CONSUMER & RETAIL =====
    "UNVR": "CONSUMER",
    "ICBP": "CONSUMER",
    "INDF": "CONSUMER",
    "MYOR": "CONSUMER",
    "KLBF": "CONSUMER",
    "ULTJ": "CONSUMER",
    "CLEO": "CONSUMER",
    "AMRT": "RETAIL",
    "RALS": "RETAIL",
    "ACES": "RETAIL",
    "ERAA": "RETAIL",
    "MAPI": "RETAIL",
    "MAPA": "RETAIL",
    "MPPA": "RETAIL",
    "KINO": "CONSUMER",

    # ===== PROPERTY =====
    "CTRA": "PROPERTY",
    "BSDE": "PROPERTY",
    "PWON": "PROPERTY",
    "ASRI": "PROPERTY",
    "SMRA": "PROPERTY",
    "BKSL": "PROPERTY",
    "DMAS": "PROPERTY",
    "APLN": "PROPERTY",
    "DILD": "PROPERTY",
    "LPKR": "PROPERTY",
    "PPRO": "PROPERTY",
    "CITY": "PROPERTY",
    "GPRA": "PROPERTY",
    "EMDE": "PROPERTY",

    # ===== INFRA / TRANSPORT =====
    "JSMR": "INFRA",
    "ASSA": "TRANSPORT",
    "WEHA": "TRANSPORT",
    "LEAD": "TRANSPORT",

    # ===== TECH / DIGITAL =====
    "GOTO": "TECH",
    "BUKA": "TECH",
    "DCII": "TECH",
    "MCAS": "TECH",
    "WIFI": "TECH",
    "EDGE": "TECH",
    "ENVY": "TECH",

    # ===== MANUFACTURING / AUTO =====
    "ASII": "MANUFACTURING",
    "AUTO": "AUTO",
    "IMAS": "AUTO",
    "GJTL": "MANUFACTURING",
    "POLY": "MANUFACTURING",
    "SMGR": "MANUFACTURING",
    "INTP": "MANUFACTURING",

    # ===== OTHERS / SPECULATIVE =====
    "SUPA": "SPECULATIVE",
    "REAL": "SPECULATIVE",
    "BKDP": "SPECULATIVE",
    "RLCO": "SPECULATIVE",
    "PANI": "SPECULATIVE",
    "SOCI": "SPECULATIVE",
    "COCO": "SPECULATIVE",
    "BIRD": "TRANSPORT",
    "BUAH": "SPECULATIVE",
    "KRYA": "SPECULATIVE",
    "IBST": "INFRA",
    "ZATA": "CONSUMER",
}