SAHAM_PROFILE = {

    # ===== BIG CAP / BLUECHIP =====
    "BBCA": "Bank Central Asia Tbk",
    "BBRI": "Bank Rakyat Indonesia Tbk",
    "BMRI": "Bank Mandiri Tbk",
    "BBNI": "Bank Negara Indonesia Tbk",
    "TLKM": "Telkom Indonesia Tbk",
    "ASII": "Astra International Tbk",
    "ICBP": "Indofood CBP Sukses Makmur Tbk",
    "INDF": "Indofood Sukses Makmur Tbk",
    "MYOR": "Mayora Indah Tbk",
    "UNVR": "Unilever Indonesia Tbk",
    "KLBF": "Kalbe Farma Tbk",
    "PGAS": "Perusahaan Gas Negara Tbk",
    "SMGR": "Semen Indonesia Tbk",
    "INTP": "Indocement Tunggal Prakarsa Tbk",

    # ===== BANK & FINANCE =====
    "ARTO": "Bank Jago Tbk",
    "BRIS": "Bank Syariah Indonesia Tbk",
    "BTPS": "Bank BTPN Syariah Tbk",
    "BNGA": "Bank CIMB Niaga Tbk",
    "BBTN": "Bank Tabungan Negara Tbk",
    "NISP": "Bank OCBC NISP Tbk",

    # ===== ENERGY & MINING =====
    "ADRO": "Adaro Energy Indonesia Tbk",
    "ITMG": "Indo Tambangraya Megah Tbk",
    "PTBA": "Bukit Asam Tbk",
    "MEDC": "Medco Energi Internasional Tbk",
    "AKRA": "AKR Corporindo Tbk",
    "ANTM": "Aneka Tambang Tbk",
    "MDKA": "Merdeka Copper Gold Tbk",
    "TINS": "Timah Tbk",
    "BRPT": "Barito Pacific Tbk",
    "HRUM": "Harum Energy Tbk",
    "INDY": "Indika Energy Tbk",
    "DOID": "Delta Dunia Makmur Tbk",
    "ELSA": "Elnusa Tbk",
    "RAJA": "Rukun Raharja Tbk",
    "PTRO": "Petrosea Tbk",
    "MBAP": "Mitrabara Adiperdana Tbk",
    "BSSR": "Baramulti Suksessarana Tbk",
    "GEMS": "Golden Energy Mines Tbk",
    "TOBA": "TBS Energi Utama Tbk",

    # ===== CONSUMER & RETAIL =====
    "ERAA": "Erajaya Swasembada Tbk",
    "ACES": "Ace Hardware Indonesia Tbk",
    "MAPI": "Mitra Adiperkasa Tbk",
    "RALS": "Ramayana Lestari Sentosa Tbk",
    "AMRT": "Sumber Alfaria Trijaya Tbk",
    "MAPA": "Map Aktif Adiperkasa Tbk",
    "MPPA": "Matahari Putra Prima Tbk",
    "CLEO": "Sariguna Primatirta Tbk",
    "ULTJ": "Ultrajaya Milk Industry & Trading Company Tbk",
    "KINO": "Kino Indonesia Tbk",
    "FAST": "Fast Food Indonesia Tbk",

    # ===== PROPERTY =====
    "CTRA": "Ciputra Development Tbk",
    "BSDE": "Bumi Serpong Damai Tbk",
    "PWON": "Pakuwon Jati Tbk",
    "ASRI": "Alam Sutera Realty Tbk",
    "SMRA": "Summarecon Agung Tbk",
    "BKSL": "Sentul City Tbk",
    "EMDE": "Megapolitan Developments Tbk",
    "DMAS": "Puradelta Lestari Tbk",
    "GPRA": "Perdana Gapuraprima Tbk",
    "PPRO": "PP Properti Tbk",
    "CITY": "Natura City Developments Tbk",
    "APLN": "Agung Podomoro Land Tbk",
    "DILD": "Intiland Development Tbk",
    "LPKR": "Lippo Karawaci Tbk",

    # ===== INFRA / TRANSPORT =====
    "JSMR": "Jasa Marga Tbk",
    "EXCL": "XL Axiata Tbk",
    "ISAT": "Indosat Ooredoo Hutchison Tbk",
    "MTEL": "Dayamitra Telekomunikasi Tbk",
    "ASSA": "Adi Sarana Armada Tbk",
    "WEHA": "WEHA Transportasi Indonesia Tbk",
    "JARR": "Jhonlin Agro Raya Tbk",
    "CSIS": "Cahayasakti Investindo Sukses Tbk",
    "IKBI": "Sumi Indo Kabel Tbk",
    "PSSI": "Pelita Samudera Shipping Tbk",

    # ===== TECH / DIGITAL =====
    "GOTO": "GoTo Gojek Tokopedia Tbk",
    "BUKA": "Bukalapak.com Tbk",
    "DCII": "DCI Indonesia Tbk",
    "MCAS": "M Cash Integrasi Tbk",
    "WIFI": "Solusi Sinergi Digital Tbk",
    "EDGE": "Indointernet Tbk",
    "ENVY": "Envy Technologies Indonesia Tbk",
    "COIN": "Indo Digital Nusantara Tbk",
    "DIVA": "Distribusi Voucher Nusantara Tbk",
    "MORA": "Mora Telematika Indonesia Tbk",

    # ===== CHEMICAL / INDUSTRIAL / HOLDING =====
    "TPIA": "Chandra Asri Pacific Tbk",
    "CUAN": "Petrindo Jaya Kreasi Tbk",
    "CDIA": "Chandra Daya Investasi Tbk",
    "PLAN": "Plaza Indonesia Realty Tbk",

    # ===== SMALL CAP / MOMENTUM / SPECULATIVE =====
    "RATU": "Ratu Prabu Energi Tbk",
    "WOWS": "Ginting Jaya Energi Tbk",
    "HELI": "Heli Surya Internusa Tbk",
    "MARK": "Mark Dynamics Indonesia Tbk",
    "SUPA": "Surya Pertiwi Tbk",
    "REAL": "Repower Asia Indonesia Tbk",
    "BKDP": "Bukit Darmo Property Tbk",
    "RLCO": "Royaltama Mulia Kontraktorindo Tbk",
    "POLY": "Asia Pacific Fibers Tbk",
    "PANI": "Pratama Abadi Nusa Industri Tbk",
    "SOCI": "Soci Mas Tbk",
    "COCO": "Wahana Interfood Nusantara Tbk",
    "BIRD": "Blue Bird Tbk",
    "BUAH": "Segar Kumala Indonesia Tbk",
    "KRYA": "Bangun Karya Perkasa Jaya Tbk",
    "GJTL": "Gajah Tunggal Tbk",
    "AUTO": "Astra Otoparts Tbk",
    "IMAS": "Indomobil Sukses Internasional Tbk",
    "BUMI": "Bumi Resources Tbk",
    "TRIM": "Trimegah Sekuritas Indonesia Tbk",
    "ZATA": "Bersama Zatta Jaya Tbk",
    "FREN": "Smartfren Telecom Tbk",
    "IBST": "Inti Bangun Sejahtera Tbk",
    "LEAD": "Logindo Samudramakmur Tbk",
}