SAHAM_PROFILE = {

    # ===== BIG CAP / BLUECHIP =====
    "BBCA": "Bank Central Asia Tbk",
    "BBRI": "Bank Rakyat Indonesia Tbk",
    "BMRI": "Bank Mandiri Tbk",
    "BBNI": "Bank Negara Indonesia Tbk",
    "TLKM": "Telkom Indonesia Tbk",
    "ASII": "Astra International Tbk",
    "ICBP": "Indofood CBP Sukses Makmur Tbk",
    "INDF": "Indofood Sukses Makmur Tbk",
    "MYOR": "Mayora Indah Tbk",
    "UNVR": "Unilever Indonesia Tbk",
    "KLBF": "Kalbe Farma Tbk",
    "PGAS": "Perusahaan Gas Negara Tbk",
    "SMGR": "Semen Indonesia Tbk",
    "INTP": "Indocement Tunggal Prakarsa Tbk",

    # ===== BANK & FINANCE =====
    "ARTO": "Bank Jago Tbk",
    "BRIS": "Bank Syariah Indonesia Tbk",
    "BTPS": "Bank BTPN Syariah Tbk",
    "BNGA": "Bank CIMB Niaga Tbk",
    "BBTN": "Bank Tabungan Negara Tbk",
    "NISP": "Bank OCBC NISP Tbk",

    # ===== ENERGY & MINING =====
    "ADRO": "Adaro Energy Indonesia Tbk",
    "ITMG": "Indo Tambangraya Megah Tbk",
    "PTBA": "Bukit Asam Tbk",
    "MEDC": "Medco Energi Internasional Tbk",
    "AKRA": "AKR Corporindo Tbk",
    "ANTM": "Aneka Tambang Tbk",
    "MDKA": "Merdeka Copper Gold Tbk",
    "TINS": "Timah Tbk",
    "BRPT": "Barito Pacific Tbk",
    "HRUM": "Harum Energy Tbk",
    "INDY": "Indika Energy Tbk",
    "DOID": "Delta Dunia Makmur Tbk",
    "ELSA": "Elnusa Tbk",
    "RAJA": "Rukun Raharja Tbk",
    "PTRO": "Petrosea Tbk",
    "MBAP": "Mitrabara Adiperdana Tbk",
    "BSSR": "Baramulti Suksessarana Tbk",
    "GEMS": "Golden Energy Mines Tbk",
    "TOBA": "TBS Energi Utama Tbk",
    "ARCI": "Archi Indonesia Tbk",
    "BREN": "Barito Renewables Energy Tbk",
    "NICL": "PAM Mineral Tbk",
    "NCKL": "Trimegah Bangun Persada Tbk",
    "PSAB": "J Resources Asia Pasifik Tbk",
    "SMRU": "SMR Utama Tbk",
    "ABMM": "ABM Investama Tbk",
    "CINT": "Chitose Internasional Tbk",
    "GOLD": "Visi Telekomunikasi Infrastruktur Tbk",
    "KKGI": "Resource Alam Indonesia Tbk",

    # ===== CONSUMER & RETAIL =====
    "ERAA": "Erajaya Swasembada Tbk",
    "ACES": "Ace Hardware Indonesia Tbk",
    "MAPI": "Mitra Adiperkasa Tbk",
    "RALS": "Ramayana Lestari Sentosa Tbk",
    "AMRT": "Sumber Alfaria Trijaya Tbk",
    "MAPA": "Map Aktif Adiperkasa Tbk",
    "MPPA": "Matahari Putra Prima Tbk",
    "CLEO": "Sariguna Primatirta Tbk",
    "ULTJ": "Ultrajaya Milk Industry & Trading Company Tbk",
    "KINO": "Kino Indonesia Tbk",
    "FAST": "Fast Food Indonesia Tbk",
    "SMAR": "Sinar Mas Agro Resources and Technology Tbk",
    "ALII": "Ancora Indonesia Resources Tbk",
    "DEPO": "Caturkarda Depo Bangunan Tbk",
    "CARE": "Metro Healthcare Indonesia Tbk",
    "DOSS": "Dosni Roha Indonesia Tbk",

    # ===== PROPERTY =====
    "CTRA": "Ciputra Development Tbk",
    "BSDE": "Bumi Serpong Damai Tbk",
    "PWON": "Pakuwon Jati Tbk",
    "ASRI": "Alam Sutera Realty Tbk",
    "SMRA": "Summarecon Agung Tbk",
    "BKSL": "Sentul City Tbk",
    "EMDE": "Megapolitan Developments Tbk",
    "DMAS": "Puradelta Lestari Tbk",
    "GPRA": "Perdana Gapuraprima Tbk",
    "PPRO": "PP Properti Tbk",
    "CITY": "Natura City Developments Tbk",
    "APLN": "Agung Podomoro Land Tbk",
    "DILD": "Intiland Development Tbk",
    "LPKR": "Lippo Karawaci Tbk",

    # ===== INFRA / TRANSPORT =====
    "JSMR": "Jasa Marga Tbk",
    "EXCL": "XL Axiata Tbk",
    "ISAT": "Indosat Ooredoo Hutchison Tbk",
    "MTEL": "Dayamitra Telekomunikasi Tbk",
    "ASSA": "Adi Sarana Armada Tbk",
    "WEHA": "WEHA Transportasi Indonesia Tbk",
    "JARR": "Jhonlin Agro Raya Tbk",
    "CSIS": "Cahayasakti Investindo Sukses Tbk",
    "IKBI": "Sumi Indo Kabel Tbk",
    "PSSI": "Pelita Samudera Shipping Tbk",
    "VKTR": "VKTR Teknologi Mobilitas Tbk",
    "KBLV": "First Media Tbk",
    "FWCT": "Wijaya Karya Beton Tbk",
    "RMKE": "RMK Energy Tbk",
    "MMLP": "Mega Manunggal Property Tbk",

    # ===== TECH / DIGITAL =====
    "GOTO": "GoTo Gojek Tokopedia Tbk",
    "BUKA": "Bukalapak.com Tbk",
    "DCII": "DCI Indonesia Tbk",
    "MCAS": "M Cash Integrasi Tbk",
    "WIFI": "Solusi Sinergi Digital Tbk",
    "EDGE": "Indointernet Tbk",
    "ENVY": "Envy Technologies Indonesia Tbk",
    "COIN": "Indo Digital Nusantara Tbk",
    "DIVA": "Distribusi Voucher Nusantara Tbk",
    "MORA": "Mora Telematika Indonesia Tbk",
    "UANG": "Pakuan Tbk",
    "AKSI": "Mineral Sumberdaya Mandiri Tbk",
    "MMIX": "Multi Indocitra Tbk",
    "DGNS": "Diagnos Laboratorium Utama Tbk",
    "TFAS": "Telefast Indonesia Tbk",
    "SOTS": "Satria Antaran Prima Tbk",

    # ===== CHEMICAL / INDUSTRIAL / HOLDING =====
    "TPIA": "Chandra Asri Pacific Tbk",
    "CUAN": "Petrindo Jaya Kreasi Tbk",
    "CDIA": "Chandra Daya Investasi Tbk",
    "PLAN": "Plaza Indonesia Realty Tbk",
    "ALKA": "Alakasa Industrindo Tbk",
    "INAI": "Indal Aluminium Industry Tbk",
    "LMPI": "Langgeng Makmur Industri Tbk",
    "GTSI": "GTS International Tbk",
    "BESS": "Batulicin Nusantara Maritim Tbk",
    "PACK": "Abadi Nusantara Hijau Investama Tbk",
    "OPMS": "Optima Prima Metal Sinergi Tbk",
    "MTRA": "Mitra Investindo Tbk",
    "TRJA": "Transkon Jaya Tbk",

    # ===== SMALL CAP / MOMENTUM / GORENGAN =====
    "LAJU": "Jasa Berdikari Logistics Tbk",
    "STAR": "Star Pacific Tbk",
    "BOGA": "Boga Dimsum Indonesia Tbk",
    "AGII": "Samator Indo Gas Tbk",
    "TAYS": "Jaya Swarasa Agung Tbk",
    "PSKT": "Red Planet Indonesia Tbk",
    "TOOL": "Sigma Energy Compressindo Tbk",
    "NETV": "Net Visi Media Tbk",
    "CASH": "Cashlez Worldwide Indonesia Tbk",
    "MPRO": "Maha Properti Indonesia Tbk",
    "NUSA": "Sinergi Megah Internusa Tbk",
    "YELO": "Yelooo Integra Datanet Tbk",
    "PURI": "Puri Global Sukses Tbk",
    "GAMA": "Gading Development Tbk",
    "MEJA": "Pelayaran Kurnia Lautan Semesta Tbk",
    "SIMA": "Siantar Top Tbk",
    "SUGI": "Sugih Energy Tbk",
    "UFOE": "Damai Sejahtera Abadi Tbk",
    "SMMT": "Golden Flower Tbk",
    "INPC": "Bank Artha Graha Internasional Tbk",
    "POLU": "Golden Eagle Energy Tbk",
    "MTSM": "Metro Realty Tbk",
    "CBMF": "Cahaya Bintang Medan Tbk",
    "HITS": "Humpuss Intermoda Transportasi Tbk",
    "ESTA": "Esta Multi Usaha Tbk",
}