SAHAM_PROFILE = {

    "AADI": "Adaro Andalan Indonesia Tbk.",
    "AALI": "Astra Agro Lestari Tbk.",
    "ABMM": "ABM Investama Tbk.",
    "ACES": "Aspirasi Hidup Indonesia Tbk.",
    "ACRO": "Samcro Hyosung Adilestari Tbk.",
    "ADCP": "Adhi Commuter Properti Tbk.",
    "ADES": "Akasha Wira International Tbk.",
    "ADHI": "Adhi Karya (Persero) Tbk.",
    "ADMF": "Adira Dinamika Multi Finance T",
    "ADMG": "Polychem Indonesia Tbk",
    "ADMR": "Alamtri Minerals Indonesia Tbk",
    "ADRO": "Alamtri Resources Indonesia Tb",
    "AEGS": "Anugerah Spareparts Sejahtera",
    "AGAR": "Asia Sejahtera Mina Tbk.",
    "AGII": "Samator Indo Gas Tbk.",
    "AGRO": "Bank Raya Indonesia Tbk.",
    "AGRS": "Bank IBK Indonesia Tbk.",
    "AHAP": "Asuransi Harta Aman Pratama Tb",
    "AIMS": "Artha Mahiya Investama Tbk.",
    "AISA": "FKS Food Sejahtera Tbk.",
    "AKPI": "Argha Karya Prima Industry Tbk",
    "AKRA": "AKR Corporindo Tbk.",
    "AKSI": "Mineral Sumberdaya Mandiri Tbk",
    "ALDO": "Alkindo Naratama Tbk.",
    "ALII": "Ancara Logistics Indonesia Tbk",
    "ALKA": "Alakasa Industrindo Tbk",
    "AMAG": "Asuransi Multi Artha Guna Tbk.",
    "AMAN": "Makmur Berkah Amanda Tbk.",
    "AMAR": "Bank Amar Indonesia Tbk.",
    "AMFG": "Asahimas Flat Glass Tbk.",
    "AMIN": "Ateliers Mecaniques D Indonesi",
    "AMMN": "Amman Mineral Internasional Tb",
    "AMMS": "Agung Menjangan Mas Tbk.",
    "AMOR": "Ashmore Asset Management Indon",
    "AMRT": "Sumber Alfaria Trijaya Tbk.",
    "ANJT": "Austindo Nusantara Jaya Tbk.",
    "ANTM": "Aneka Tambang Tbk.",
    "APEX": "Apexindo Pratama Duta Tbk.",
    "APIC": "Pacific Strategic Financial Tb",
    "APII": "Arita Prima Indonesia Tbk.",
    "APLI": "Asiaplast Industries Tbk.",
    "APLN": "Agung Podomoro Land Tbk.",
    "ARCI": "Archi Indonesia Tbk.",
    "AREA": "Dunia Virtual Online Tbk.",
    "ARGO": "Argo Pantes Tbk",
    "ARII": "Atlas Resources Tbk.",
    "ARKO": "Arkora Hydro Tbk.",
    "ARNA": "Arwana Citramulia Tbk.",
    "ARTA": "Arthavest Tbk",
    "ARTO": "Bank Jago Tbk.",
    "ASBI": "Asuransi Bintang Tbk.",
    "ASDM": "Asuransi Dayin Mitra Tbk.",
    "ASGR": "Astra Graphia Tbk.",
    "ASHA": "Cilacap Samudera Fishing Indus",
    "ASII": "Astra International Tbk.",
    "ASJT": "Asuransi Jasa Tania Tbk.",
    "ASLC": "Autopedia Sukses Lestari Tbk.",
    "ASLI": "Asri Karya Lestari Tbk.",
    "ASPI": "Andalan Sakti Primaindo Tbk.",
    "ASRI": "Alam Sutera Realty Tbk.",
    "ASRM": "Asuransi Ramayana Tbk.",
    "ASSA": "Adi Sarana Armada Tbk.",
    "ATAP": "Trimitra Prawara Goldland Tbk.",
    "ATIC": "Anabatic Technologies Tbk.",
    "ATLA": "Atlantis Subsea Indonesia Tbk.",
    "AUTO": "Astra Otoparts Tbk.",
    "AVIA": "Avia Avian Tbk.",
    "AWAN": "Era Digital Media Tbk.",
    "AXIO": "Tera Data Indonusa Tbk.",
    "AYAM": "Janu Putra Sejahtera Tbk.",
    "AYLS": "Agro Yasa Lestari Tbk.",
    "BABP": "Bank MNC Internasional Tbk.",
    "BABY": "Multitrend Indo Tbk.",
    "BACA": "Bank Capital Indonesia Tbk.",
    "BAIK": "Bersama Mencapai Puncak Tbk.",
    "BAJA": "Saranacentral Bajatama Tbk.",
    "BALI": "Bali Towerindo Sentra Tbk.",
    "BANK": "Bank Aladin Syariah Tbk.",
    "BAPA": "Bekasi Asri Pemula Tbk.",
    "BATR": "Benteng Api Technic Tbk.",
    "BAYU": "Bayu Buana Tbk",
    "BBCA": "Bank Central Asia Tbk.",
    "BBHI": "Allo Bank Indonesia Tbk.",
    "BBKP": "Bank KB Indonesia Tbk.",
    "BBLD": "Buana Finance Tbk.",
    "BBMD": "Bank Mestika Dharma Tbk.",
    "BBNI": "Bank Negara Indonesia (Persero",
    "BBRI": "Bank Rakyat Indonesia (Persero",
    "BBRM": "Pelayaran Nasional Bina Buana",
    "BBSI": "Krom Bank Indonesia Tbk.",
    "BBSS": "Bumi Benowo Sukses Sejahtera T",
    "BBTN": "Bank Tabungan Negara (Persero)",
    "BBYB": "Bank Neo Commerce Tbk.",
    "BCAP": "MNC Kapital Indonesia Tbk.",
    "BCIC": "Bank JTrust Indonesia Tbk.",
    "BCIP": "Bumi Citra Permai Tbk.",
    "BDKR": "Berdikari Pondasi Perkasa Tbk.",
    "BDMN": "Bank Danamon Indonesia Tbk.",
    "BEEF": "Estika Tata Tiara Tbk.",
    "BEER": "Jobubu Jarum Minahasa Tbk.",
    "BELI": "Global Digital Niaga Tbk.",
    "BELL": "Trisula Textile Industries Tbk",
    "BESS": "Batulicin Nusantara Maritim Tb",
    "BEST": "Bekasi Fajar Industrial Estate",
    "BFIN": "BFI Finance  Indonesia Tbk.",
    "BGTG": "Bank Ganesha Tbk.",
    "BHAT": "Bhakti Multi Artha Tbk.",
    "BIKE": "Sepeda Bersama Indonesia Tbk.",
    "BINA": "Bank Ina Perdana Tbk.",
    "BINO": "Perma Plasindo Tbk.",
    "BIPI": "Astrindo Nusantara Infrastrukt",
    "BIPP": "Bhuwanatala Indah Permai Tbk.",
    "BIRD": "Blue Bird Tbk.",
    "BISI": "BISI International Tbk.",
    "BJBR": "Bank Pembangunan Daerah Jawa B",
    "BJTM": "Bank Pembangunan Daerah Jawa T",
    "BKSL": "Sentul City Tbk.",
    "BKSW": "Bank QNB Indonesia Tbk.",
    "BLES": "Superior Prima Sukses Tbk.",
    "BLOG": "Trimitra Trans Persada Tbk.",
    "BLUE": "Berkah Prima Perkasa Tbk.",
    "BMAS": "Bank Maspion Indonesia Tbk.",
    "BMBL": "Lavender Bina Cendikia Tbk.",
    "BMHS": "Bundamedik Tbk.",
    "BMRI": "Bank Mandiri (Persero) Tbk.",
    "BMSR": "Bintang Mitra Semestaraya Tbk",
    "BMTR": "Global Mediacom Tbk.",
    "BNBA": "Bank Bumi Arta Tbk.",
    "BNBR": "Bakrie & Brothers Tbk",
    "BNGA": "Bank CIMB Niaga Tbk.",
    "BNII": "Bank Maybank Indonesia Tbk.",
    "BNLI": "Bank Permata Tbk.",
    "BOAT": "Newport Marine Services Tbk.",
    "BOBA": "Formosa Ingredient Factory Tbk",
    "BOGA": "Apollo Global Interactive Tbk.",
    "BOLA": "Bali Bintang Sejahtera Tbk.",
    "BOLT": "Garuda Metalindo Tbk.",
    "BPFI": "Woori Finance Indonesia Tbk.",
    "BPII": "Batavia Prosperindo Internasio",
    "BPTR": "Batavia Prosperindo Trans Tbk.",
    "BRAM": "Indo Kordsa Tbk.",
    "BREN": "Barito Renewables Energy Tbk.",
    "BRIS": "Bank Syariah Indonesia (Perser",
    "BRMS": "Bumi Resources Minerals Tbk.",
    "BRNA": "Berlina Tbk.",
    "BRPT": "Barito Pacific Tbk.",
    "BRRC": "Raja Roti Cemerlang Tbk.",
    "BSBK": "Wulandari Bangun Laksana Tbk.",
    "BSDE": "Bumi Serpong Damai Tbk.",
    "BSIM": "Bank Sinarmas Tbk.",
    "BSML": "Bintang Samudera Mandiri Lines",
    "BSSR": "Baramulti Suksessarana Tbk.",
    "BTON": "Betonjaya Manunggal Tbk.",
    "BTPN": "Bank SMBC Indonesia Tbk.",
    "BTPS": "Bank BTPN Syariah Tbk.",
    "BUAH": "Segar Kumala Indonesia Tbk.",
    "BUDI": "Budi Starch & Sweetener Tbk.",
    "BUKA": "Bukalapak.com Tbk.",
    "BUKK": "Bukaka Teknik Utama Tbk.",
    "BULL": "Buana Lintas Lautan Tbk.",
    "BUMI": "Bumi Resources Tbk.",
    "BUVA": "Bukit Uluwatu Villa Tbk.",
    "BVIC": "Bank Victoria International Tb",
    "BWPT": "Eagle High Plantations Tbk.",
    "BYAN": "Bayan Resources Tbk.",
    "CAKK": "Cahayaputra Asa Keramik Tbk.",
    "CAMP": "Campina Ice Cream Industry Tbk",
    "CARE": "Metro Healthcare Indonesia Tbk",
    "CARS": "Industri dan Perdagangan Bintr",
    "CASA": "Capital Financial Indonesia Tb",
    "CASH": "Cashlez Worldwide Indonesia Tb",
    "CASS": "Cahaya Aero Services Tbk.",
    "CBDK": "Bangun Kosambi Sukses Tbk.",
    "CBPE": "Citra Buana Prasida Tbk.",
    "CBRE": "Cakra Buana Resources Energi T",
    "CBUT": "Citra Borneo Utama Tbk.",
    "CCSI": "Communication Cable Systems In",
    "CDIA": "Chandra Daya Investasi Tbk.",
    "CEKA": "Wilmar Cahaya Indonesia Tbk.",
    "CENT": "Centratama Telekomunikasi Indo",
    "CFIN": "Clipan Finance Indonesia Tbk.",
    "CGAS": "Citra Nusantara Gemilang Tbk.",
    "CHEK": "Diastika Biotekindo Tbk.",
    "CHEM": "Chemstar Indonesia Tbk.",
    "CHIP": "Pelita Teknologi Global Tbk.",
    "CINT": "Chitose Internasional Tbk.",
    "CITA": "Cita Mineral Investindo Tbk.",
    "CITY": "Natura City Developments Tbk.",
    "CLAY": "Citra Putra Realty Tbk.",
    "CLEO": "Sariguna Primatirta Tbk.",
    "CLPI": "Colorpak Indonesia Tbk.",
    "CMNP": "Citra Marga Nusaphala Persada",
    "CMNT": "Cemindo Gemilang Tbk.",
    "CMRY": "Cisarua Mountain Dairy Tbk.",
    "CNMA": "Nusantara Sejahtera Raya Tbk.",
    "COAL": "Black Diamond Resources Tbk.",
    "COCO": "Wahana Interfood Nusantara Tbk",
    "COIN": "Indokripto Koin Semesta Tbk.",
    "CPIN": "Charoen Pokphand Indonesia Tbk",
    "CPRO": "Central Proteina Prima Tbk.",
    "CRAB": "Toba Surimi Industries Tbk.",
    "CRSN": "Carsurin Tbk.",
    "CSAP": "Catur Sentosa Adiprana Tbk.",
    "CSIS": "Cahayasakti Investindo Sukses",
    "CSMI": "Cipta Selera Murni Tbk.",
    "CSRA": "Cisadane Sawit Raya Tbk.",
    "CTBN": "Citra Tubindo Tbk.",
    "CTRA": "Ciputra Development Tbk.",
    "CTTH": "Citatah Tbk.",
    "CUAN": "Petrindo Jaya Kreasi Tbk.",
    "CYBR": "ITSEC Asia Tbk.",
    "DAAZ": "Daaz Bara Lestari Tbk.",
    "DADA": "Diamond Citra Propertindo Tbk.",
    "DART": "Duta Anggada Realty Tbk.",
    "DATA": "Remala Abadi Tbk.",
    "DAYA": "Duta Intidaya Tbk.",
    "DCII": "DCI Indonesia Tbk.",
    "DEFI": "Danasupra Erapacific Tbk.",
    "DEPO": "Caturkarda Depo Bangunan Tbk.",
    "DEWA": "Darma Henwa Tbk",
    "DEWI": "Dewi Shri Farmindo Tbk.",
    "DFAM": "Dafam Property Indonesia Tbk.",
    "DGIK": "Nusa Konstruksi Enjiniring Tbk",
    "DGNS": "Diagnos Laboratorium Utama Tbk",
    "DGWG": "Delta Giri Wacana Tbk.",
    "DILD": "Intiland Development Tbk.",
    "DIVA": "Distribusi Voucher Nusantara T",
    "DKFT": "Central Omega Resources Tbk.",
    "DKHH": "Cipta Sarana Medika Tbk.",
    "DLTA": "Delta Djakarta Tbk.",
    "DMAS": "Puradelta Lestari Tbk.",
    "DMMX": "Digital Mediatama Maxima Tbk.",
    "DMND": "Diamond Food Indonesia Tbk.",
    "DNAR": "Bank Oke Indonesia Tbk.",
    "DNET": "Indoritel Makmur Internasional",
    "DOID": "BUMA Internasional Grup Tbk.",
    "DOOH": "Era Media Sejahtera Tbk.",
    "DOSS": "Global Sukses Digital Tbk.",
    "DPNS": "Duta Pertiwi Nusantara Tbk.",
    "DPUM": "Dua Putra Utama Makmur Tbk.",
    "DRMA": "Dharma Polimetal Tbk.",
    "DSFI": "Dharma Samudera Fishing Indust",
    "DSNG": "Dharma Satya Nusantara Tbk.",
    "DSSA": "Dian Swastatika Sentosa Tbk",
    "DUTI": "Duta Pertiwi Tbk",
    "DVLA": "Darya-Varia Laboratoria Tbk.",
    "DWGL": "Dwi Guna Laksana Tbk.",
    "DYAN": "Dyandra Media International Tb",
    "EAST": "Eastparc Hotel Tbk.",
    "ECII": "Electronic City Indonesia Tbk.",
    "EDGE": "Indointernet Tbk.",
    "EKAD": "Ekadharma International Tbk.",
    "ELIT": "Data Sinergitama Jaya Tbk.",
    "ELPI": "Pelayaran Nasional Ekalya Purn",
    "ELSA": "Elnusa Tbk.",
    "EMAS": "Merdeka Gold Resources Tbk.",
    "EMDE": "Megapolitan Developments Tbk.",
    "EMTK": "Elang Mahkota Teknologi Tbk.",
    "ENAK": "Champ Resto Indonesia Tbk.",
    "ENRG": "Energi Mega Persada Tbk.",
    "ENZO": "Morenzo Abadi Perkasa Tbk.",
    "EPMT": "Enseval Putera Megatrading Tbk",
    "ERAA": "Erajaya Swasembada Tbk.",
    "ERAL": "Sinar Eka Selaras Tbk.",
    "ERTX": "Eratex Djaja Tbk.",
    "ESIP": "Sinergi Inti Plastindo Tbk.",
    "ESSA": "ESSA Industries Indonesia Tbk.",
    "ESTA": "Esta Multi Usaha Tbk.",
    "ESTI": "Ever Shine Tex Tbk.",
    "EURO": "Estee Gold Feet Tbk.",
    "EXCL": "XLSMART Telecom Sejahtera Tbk.",
    "FAPA": "FAP Agri Tbk.",
    "FAST": "Fast Food Indonesia Tbk.",
    "FILM": "MD Entertainment Tbk.",
    "FIRE": "Alfa Energi Investama Tbk.",
    "FISH": "FKS Multi Agro Tbk.",
    "FITT": "Hotel Fitra International Tbk.",
    "FLMC": "Falmaco Nonwoven Industri Tbk.",
    "FMII": "Fortune Mate Indonesia Tbk",
    "FOLK": "Multi Garam Utama Tbk.",
    "FORE": "Fore Kopi Indonesia Tbk.",
    "FORU": "Fortune Indonesia Tbk",
    "FPNI": "Lotte Chemical Titan Tbk.",
    "FUJI": "Fuji Finance Indonesia Tbk.",
    "FUTR": "Futura Energi Global Tbk.",
    "FWCT": "Wijaya Cahaya Timber Tbk.",
    "GDST": "Gunawan Dianjaya Steel Tbk.",
    "GDYR": "Goodyear Indonesia Tbk.",
    "GEMA": "Gema Grahasarana Tbk.",
    "GEMS": "Golden Energy Mines Tbk.",
    "GGRM": "Gudang Garam Tbk.",
    "GGRP": "Gunung Raja Paksi Tbk.",
    "GHON": "Gihon Telekomunikasi Indonesia",
    "GIAA": "Garuda Indonesia (Persero) Tbk",
    "GJTL": "Gajah Tunggal Tbk.",
    "GLVA": "Galva Technologies Tbk.",
    "GMFI": "Garuda Maintenance Facility Ae",
    "GMTD": "Gowa Makassar Tourism Developm",
    "GOLD": "Visi Telekomunikasi Infrastruk",
    "GOLF": "Intra Golflink Resorts Tbk.",
    "GOOD": "Garudafood Putra Putri Jaya Tb",
    "GOTO": "GoTo Gojek Tokopedia Tbk.",
    "GPRA": "Perdana Gapuraprima Tbk.",
    "GPSO": "Geoprima Solusi Tbk.",
    "GRIA": "Ingria Pratama Capitalindo Tbk",
    "GRPH": "Griptha Putra Persada Tbk.",
    "GRPM": "Graha Prima Mentari Tbk.",
    "GSMF": "Equity Development Investment",
    "GTBO": "Garda Tujuh Buana Tbk",
    "GTRA": "Grahaprima Suksesmandiri Tbk.",
    "GTSI": "GTS Internasional Tbk.",
    "GULA": "Aman Agrindo Tbk.",
    "GUNA": "Gunanusa Eramandiri Tbk.",
    "GWSA": "Greenwood Sejahtera Tbk.",
    "GZCO": "Gozco Plantations Tbk.",
    "HAIS": "Hasnur Internasional Shipping",
    "HAJJ": "Arsy Buana Travelindo Tbk.",
    "HALO": "Haloni Jane Tbk.",
    "HATM": "Habco Trans Maritima Tbk.",
    "HBAT": "Minahasa Membangun Hebat Tbk.",
    "HDFA": "Radana Bhaskara Finance Tbk.",
    "HDIT": "Hensel Davest Indonesia Tbk.",
    "HEAL": "Medikaloka Hermina Tbk.",
    "HELI": "Jaya Trishindo Tbk.",
    "HERO": "DFI Retail Nusantara Tbk.",
    "HEXA": "Hexindo Adiperkasa Tbk.",
    "HGII": "Hero Global Investment Tbk.",
    "HMSP": "H.M. Sampoerna Tbk.",
    "HOKI": "Buyung Poetra Sembada Tbk.",
    "HOMI": "Grand House Mulia Tbk.",
    "HOPE": "Harapan Duta Pertiwi Tbk.",
    "HRTA": "Hartadinata Abadi Tbk.",
    "HRUM": "Harum Energy Tbk.",
    "HUMI": "Humpuss Maritim Internasional",
    "HYGN": "Ecocare Indo Pasifik Tbk.",
    "IATA": "MNC Energy Investments Tbk.",
    "IBOS": "Indo Boga Sukses Tbk.",
    "ICBP": "Indofood CBP Sukses Makmur Tbk",
    "ICON": "Island Concepts Indonesia Tbk.",
    "IDEA": "Idea Indonesia Akademi Tbk.",
    "IDPR": "Indonesia Pondasi Raya Tbk.",
    "IFII": "Indonesia Fibreboard Industry",
    "IFSH": "Ifishdeco Tbk.",
    "IGAR": "Champion Pacific Indonesia Tbk",
    "IKAN": "Era Mandiri Cemerlang Tbk.",
    "IKBI": "Sumi Indo Kabel Tbk.",
    "IKPM": "Ikapharmindo Putramas Tbk.",
    "IMAS": "Indomobil Sukses Internasional",
    "IMJS": "Indomobil Multi Jasa Tbk.",
    "IMPC": "Impack Pratama Industri Tbk.",
    "INAI": "Indal Aluminium Industry Tbk.",
    "INCF": "Indo Komoditi Korpora Tbk.",
    "INCI": "Intanwijaya Internasional Tbk",
    "INCO": "Vale Indonesia Tbk.",
    "INDF": "Indofood Sukses Makmur Tbk.",
    "INDO": "Royalindo Investa Wijaya Tbk.",
    "INDR": "Indo-Rama Synthetics Tbk.",
    "INDS": "Indospring Tbk.",
    "INDX": "Tanah Laut Tbk",
    "INDY": "Indika Energy Tbk.",
    "INET": "Sinergi Inti Andalan Prima Tbk",
    "INKP": "Indah Kiat Pulp & Paper Tbk.",
    "INOV": "Inocycle Technology Group Tbk.",
    "INPC": "Bank Artha Graha Internasional",
    "INPP": "Indonesian Paradise Property T",
    "INRU": "Toba Pulp Lestari Tbk.",
    "INTD": "Inter Delta Tbk",
    "INTP": "Indocement Tunggal Prakarsa Tb",
    "IOTF": "Sumber Sinergi Makmur Tbk.",
    "IPAC": "Era Graharealty Tbk.",
    "IPCC": "Indonesia Kendaraan Terminal T",
    "IPCM": "Jasa Armada Indonesia Tbk.",
    "IPOL": "Indopoly Swakarsa Industry Tbk",
    "IRRA": "Itama Ranoraya Tbk.",
    "IRSX": "Folago Global Nusantara Tbk.",
    "ISAP": "Isra Presisi Indonesia Tbk.",
    "ISAT": "Indosat Tbk.",
    "ISEA": "Indo American Seafoods Tbk.",
    "ISSP": "Steel Pipe Industry of Indones",
    "ITIC": "Indonesian Tobacco Tbk.",
    "ITMA": "Sumber Energi Andalan Tbk.",
    "ITMG": "Indo Tambangraya Megah Tbk.",
    "JARR": "Jhonlin Agro Raya Tbk.",
    "JAST": "Jasnita Telekomindo Tbk.",
    "JATI": "Informasi Teknologi Indonesia",
    "JAWA": "Jaya Agra Wattie Tbk.",
    "JAYA": "Armada Berjaya Trans Tbk.",
    "JECC": "Jembo Cable Company Tbk.",
    "JIHD": "Jakarta International Hotels &",
    "JKON": "Jaya Konstruksi Manggala Prata",
    "JMAS": "Asuransi Jiwa Syariah Jasa Mit",
    "JPFA": "Japfa Comfeed Indonesia Tbk.",
    "JRPT": "Jaya Real Property Tbk.",
    "JSMR": "Jasa Marga (Persero) Tbk.",
    "JSPT": "Jakarta Setiabudi Internasiona",
    "JTPE": "Jasuindo Tiga Perkasa Tbk.",
    "KAEF": "Kimia Farma Tbk.",
    "KAQI": "Jantra Grupo Indonesia Tbk.",
    "KBLI": "KMI Wire & Cable Tbk.",
    "KBLM": "Kabelindo Murni Tbk.",
    "KBLV": "First Media Tbk.",
    "KDSI": "Kedawung Setia Industrial Tbk.",
    "KDTN": "Puri Sentul Permai Tbk.",
    "KEEN": "Kencana Energi Lestari Tbk.",
    "KEJU": "Mulia Boga Raya Tbk.",
    "KETR": "Ketrosden Triasmitra Tbk.",
    "KICI": "Kedaung Indah Can Tbk",
    "KIJA": "Kawasan Industri Jababeka Tbk.",
    "KING": "Hoffmen Cleanindo Tbk.",
    "KINO": "Kino Indonesia Tbk.",
    "KIOS": "Kioson Komersial Indonesia Tbk",
    "KJEN": "Krida Jaringan Nusantara Tbk.",
    "KKGI": "Resource Alam Indonesia Tbk.",
    "KLAS": "Pelayaran Kurnia Lautan Semest",
    "KLBF": "Kalbe Farma Tbk.",
    "KLIN": "Klinko Karya Imaji Tbk.",
    "KMDS": "Kurniamitra Duta Sentosa Tbk.",
    "KMTR": "Kirana Megatara Tbk.",
    "KOBX": "Kobexindo Tractors Tbk.",
    "KOCI": "Kokoh Exa Nusantara Tbk.",
    "KOKA": "Koka Indonesia Tbk.",
    "KONI": "Perdana Bangun Pusaka Tbk",
    "KOPI": "Mitra Energi Persada Tbk.",
    "KOTA": "DMS Propertindo Tbk.",
    "KPIG": "MNC Tourism Indonesia Tbk.",
    "KRAS": "Krakatau Steel (Persero) Tbk.",
    "KRYA": "Bangun Karya Perkasa Jaya Tbk.",
    "KSIX": "Kentanix Supra International T",
    "KUAS": "Ace Oldfields Tbk.",
    "LABA": "Green Power Group Tbk.",
    "LABS": "UBC Medical Indonesia Tbk.",
    "LAJU": "Jasa Berdikari Logistics Tbk.",
    "LAND": "Trimitra Propertindo Tbk.",
    "LAPD": "Leyand International Tbk.",
    "LCKM": "LCK Global Kedaton Tbk.",
    "LEAD": "Logindo Samudramakmur Tbk.",
    "LFLO": "Imago Mulia Persada Tbk.",
    "LIFE": "MSIG Life Insurance Indonesia",
    "LINK": "Link Net Tbk.",
    "LION": "Lion Metal Works Tbk.",
    "LIVE": "Homeco Victoria Makmur Tbk.",
    "LMAX": "Lupromax Pelumas Indonesia Tbk",
    "LMPI": "Langgeng Makmur Industri Tbk.",
    "LOPI": "Logisticsplus International Tb",
    "LPCK": "Lippo Cikarang Tbk",
    "LPGI": "Lippo General Insurance Tbk.",
    "LPIN": "Multi Prima Sejahtera Tbk",
    "LPKR": "Lippo Karawaci Tbk.",
    "LPLI": "Star Pacific Tbk",
    "LPPF": "Matahari Department Store Tbk.",
    "LPPS": "Lenox Pasifik Investama Tbk.",
    "LRNA": "Eka Sari Lorena Transport Tbk.",
    "LSIP": "PP London Sumatra Indonesia Tb",
    "LTLS": "Lautan Luas Tbk.",
    "LUCK": "Sentral Mitra Informatika Tbk.",
    "LUCY": "Lima Dua Lima Tiga Tbk.",
    "MAHA": "Mandiri Herindo Adiperkasa Tbk",
    "MAIN": "Malindo Feedmill Tbk.",
    "MANG": "Manggung Polahraya Tbk.",
    "MAPA": "Map Aktif Adiperkasa Tbk.",
    "MAPB": "MAP Boga Adiperkasa Tbk.",
    "MAPI": "Mitra Adiperkasa Tbk.",
    "MARK": "Mark Dynamics Indonesia Tbk.",
    "MASB": "Bank Multiarta Sentosa Tbk.",
    "MAXI": "Maxindo Karya Anugerah Tbk.",
    "MAYA": "Bank Mayapada Internasional Tb",
    "MBAP": "Mitrabara Adiperdana Tbk.",
    "MBMA": "Merdeka Battery Materials Tbk.",
    "MBSS": "Mitrabahtera Segara Sejati Tbk",
    "MBTO": "Martina Berto Tbk.",
    "MCAS": "M Cash Integrasi Tbk.",
    "MCOL": "Prima Andalan Mandiri Tbk.",
    "MCOR": "Bank China Construction Bank I",
    "MDIA": "Intermedia Capital Tbk.",
    "MDIY": "Daya Intiguna Yasa Tbk.",
    "MDKA": "Merdeka Copper Gold Tbk.",
    "MDKI": "Emdeki Utama Tbk.",
    "MDLA": "Medela Potentia Tbk.",
    "MDLN": "Modernland Realty Tbk.",
    "MEDC": "Medco Energi Internasional Tbk",
    "MEDS": "Hetzer Medical Indonesia Tbk.",
    "MEGA": "Bank Mega Tbk.",
    "MEJA": "Harta Djaya Karya Tbk.",
    "MERI": "Merry Riana Edukasi Tbk.",
    "MERK": "Merck Tbk.",
    "META": "Nusantara Infrastructure Tbk.",
    "MGLV": "Panca Anugrah Wisesa Tbk.",
    "MGNA": "Magna Investama Mandiri Tbk.",
    "MGRO": "Mahkota Group Tbk.",
    "MHKI": "Multi Hanna Kreasindo Tbk.",
    "MICE": "Multi Indocitra Tbk.",
    "MIDI": "Midi Utama Indonesia Tbk.",
    "MIKA": "Mitra Keluarga Karyasehat Tbk.",
    "MINA": "Sanurhasta Mitra Tbk.",
    "MINE": "Sinar Terang Mandiri Tbk.",
    "MITI": "Mitra Investindo Tbk.",
    "MKAP": "Multikarya Asia Pasifik Raya T",
    "MKPI": "Metropolitan Kentjana Tbk.",
    "MKTR": "Menthobi Karyatama Raya Tbk.",
    "MLBI": "Multi Bintang Indonesia Tbk.",
    "MLIA": "Mulia Industrindo Tbk",
    "MLPL": "Multipolar Tbk.",
    "MLPT": "Multipolar Technology Tbk.",
    "MMIX": "Multi Medika Internasional Tbk",
    "MMLP": "Mega Manunggal Property Tbk.",
    "MNCN": "Media Nusantara Citra Tbk.",
    "MOLI": "Madusari Murni Indah Tbk.",
    "MORA": "Mora Telematika Indonesia Tbk.",
    "MPIX": "Mitra Pedagang Indonesia Tbk.",
    "MPMX": "Mitra Pinasthika Mustika Tbk.",
    "MPOW": "Megapower Makmur Tbk.",
    "MPRO": "Maha Properti Indonesia Tbk.",
    "MPXL": "MPX Logistics International Tb",
    "MRAT": "Mustika Ratu Tbk.",
    "MREI": "Maskapai Reasuransi Indonesia",
    "MSIE": "Multisarana Intan Eduka Tbk.",
    "MSIN": "MNC Digital Entertainment Tbk.",
    "MSJA": "Multi Spunindo Jaya Tbk.",
    "MSKY": "MNC Sky Vision Tbk.",
    "MSTI": "Mastersystem Infotama Tbk.",
    "MTDL": "Metrodata Electronics Tbk.",
    "MTEL": "Dayamitra Telekomunikasi Tbk.",
    "MTLA": "Metropolitan Land Tbk.",
    "MTMH": "Murni Sadar Tbk.",
    "MTWI": "Malacca Trust Wuwungan Insuran",
    "MUTU": "Mutuagung Lestari Tbk.",
    "MYOH": "Samindo Resources Tbk.",
    "MYOR": "Mayora Indah Tbk.",
    "NAIK": "Adiwarna Anugerah Abadi Tbk.",
    "NANO": "Nanotech Indonesia Global Tbk.",
    "NASI": "Wahana Inti Makmur Tbk.",
    "NATO": "Olympus Strategic Indonesia Tb",
    "NAYZ": "Hassana Boga Sejahtera Tbk.",
    "NCKL": "Trimegah Bangun Persada Tbk.",
    "NELY": "Pelayaran Nelly Dwi Putri Tbk.",
    "NEST": "Esta Indonesia Tbk.",
    "NETV": "MDTV Media Technologies Tbk.",
    "NFCX": "NFC Indonesia Tbk.",
    "NICE": "Adhi Kartiko Pratama Tbk.",
    "NICK": "Charnic Capital Tbk.",
    "NICL": "PAM Mineral Tbk.",
    "NIKL": "Pelat Timah Nusantara Tbk.",
    "NINE": "Techno9 Indonesia Tbk.",
    "NIRO": "City Retail Developments Tbk.",
    "NISP": "Bank OCBC NISP Tbk.",
    "NOBU": "Bank Nationalnobu Tbk.",
    "NPGF": "Nusa Palapa Gemilang Tbk.",
    "NRCA": "Nusa Raya Cipta Tbk.",
    "NSSS": "Nusantara Sawit Sejahtera Tbk.",
    "NTBK": "Nusatama Berkah Tbk.",
    "NZIA": "Nusantara Almazia Tbk.",
    "OASA": "Maharaksa Biru Energi Tbk.",
    "OBAT": "Brigit Biofarmaka Teknologi Tb",
    "OBMD": "OBM Drilchem Tbk.",
    "OILS": "Indo Oil Perkasa Tbk.",
    "OKAS": "Ancora Indonesia Resources Tbk",
    "OLIV": "Oscar Mitra Sukses Sejahtera T",
    "OMED": "Jayamas Medica Industri Tbk.",
    "OPMS": "Optima Prima Metal Sinergi Tbk",
    "PACK": "Abadi Nusantara Hijau Investam",
    "PADA": "Personel Alih Daya Tbk.",
    "PADI": "Minna Padi Investama Sekuritas",
    "PALM": "Provident Investasi Bersama Tb",
    "PAMG": "Bima Sakti Pertiwi Tbk.",
    "PANI": "Pantai Indah Kapuk Dua Tbk.",
    "PANR": "Panorama Sentrawisata Tbk.",
    "PANS": "Panin Sekuritas Tbk.",
    "PART": "Cipta Perdana Lancar Tbk.",
    "PBID": "Panca Budi Idaman Tbk.",
    "PBSA": "Paramita Bangun Sarana Tbk.",
    "PDES": "Destinasi Tirta Nusantara Tbk",
    "PDPP": "Primadaya Plastisindo Tbk.",
    "PEGE": "Panca Global Kapital Tbk.",
    "PEHA": "Phapros Tbk.",
    "PEVE": "Penta Valent Tbk.",
    "PGAS": "Perusahaan Gas Negara (Persero",
    "PGEO": "Pertamina Geothermal Energy Tb",
    "PGLI": "Pembangunan Graha Lestari Inda",
    "PGUN": "Pradiksi Gunatama Tbk.",
    "PICO": "Pelangi Indah Canindo Tbk",
    "PIPA": "Multi Makmur Lemindo Tbk.",
    "PJAA": "Pembangunan Jaya Ancol Tbk.",
    "PJHB": "Pelayaran Jaya Hidup Baru Tbk.",
    "PKPK": "Paragon Karya Perkasa Tbk.",
    "PLAN": "Planet Properindo Jaya Tbk.",
    "PMJS": "Putra Mandiri Jembar Tbk.",
    "PMUI": "Prima Multi Usaha Indonesia Tb",
    "PNBN": "Bank Pan Indonesia Tbk",
    "PNBS": "Bank Panin Dubai Syariah Tbk.",
    "PNGO": "Pinago Utama Tbk.",
    "PNIN": "Paninvest Tbk.",
    "PNLF": "Panin Financial Tbk.",
    "PNSE": "Pudjiadi & Sons Tbk.",
    "POLA": "Pool Advista Finance Tbk.",
    "POLI": "Pollux Hotels Group Tbk.",
    "POLU": "Golden Flower Tbk.",
    "PORT": "Nusantara Pelabuhan Handal Tbk",
    "POWR": "Cikarang Listrindo Tbk.",
    "PPGL": "Prima Globalindo Logistik Tbk.",
    "PPRE": "PP Presisi Tbk.",
    "PPRI": "Paperocks Indonesia Tbk.",
    "PRAY": "Famon Awal Bros Sedaya Tbk.",
    "PRDA": "Prodia Widyahusada Tbk.",
    "PRIM": "Royal Prima Tbk.",
    "PSAB": "J Resources Asia Pasifik Tbk.",
    "PSAT": "Pancaran Samudera Transport Tb",
    "PSDN": "Prasidha Aneka Niaga Tbk",
    "PSGO": "Palma Serasih Tbk.",
    "PSKT": "Red Planet Indonesia Tbk.",
    "PSSI": "IMC Pelita Logistik Tbk.",
    "PTBA": "Bukit Asam (Persero) Tbk.",
    "PTIS": "Indo Straits Tbk.",
    "PTMP": "Mitra Pack Tbk.",
    "PTPP": "PP (Persero) Tbk.",
    "PTPS": "Pulau Subur Tbk.",
    "PTPW": "Pratama Widya Tbk.",
    "PTRO": "Petrosea Tbk.",
    "PTSN": "Sat Nusapersada Tbk",
    "PTSP": "Pioneerindo Gourmet Internatio",
    "PUDP": "Pudjiadi Prestige Tbk.",
    "PURI": "Puri Global Sukses Tbk.",
    "PWON": "Pakuwon Jati Tbk.",
    "PYFA": "Pyridam Farma Tbk",
    "PZZA": "Sarimelati Kencana Tbk.",
    "RAAM": "Tripar Multivision Plus Tbk.",
    "RAJA": "Rukun Raharja Tbk.",
    "RALS": "Ramayana Lestari Sentosa Tbk.",
    "RANC": "Supra Boga Lestari Tbk.",
    "RATU": "Raharja Energi Cepu Tbk.",
    "RCCC": "Utama Radar Cahaya Tbk.",
    "RDTX": "Roda Vivatex Tbk",
    "REAL": "Repower Asia Indonesia Tbk.",
    "RELF": "Graha Mitra Asia Tbk.",
    "RELI": "Reliance Sekuritas Indonesia T",
    "RGAS": "Kian Santang Muliatama Tbk.",
    "RICY": "Ricky Putra Globalindo Tbk",
    "RIGS": "Rig Tenders Indonesia Tbk.",
    "RISE": "Jaya Sukses Makmur Sentosa Tbk",
    "RLCO": "Abadi Lestari Indonesia Tbk.",
    "RMKE": "RMK Energy Tbk.",
    "RMKO": "Royaltama Mulia Kontraktorindo",
    "ROCK": "Rockfields Properti Indonesia",
    "RODA": "Pikko Land Development Tbk.",
    "RONY": "Aracord Nusantara Group Tbk.",
    "ROTI": "Nippon Indosari Corpindo Tbk.",
    "RSCH": "Charlie Hospital Semarang Tbk.",
    "RUIS": "Radiant Utama Interinsco Tbk.",
    "RUNS": "Global Sukses Solusi Tbk.",
    "SAFE": "Steady Safe Tbk",
    "SAME": "Sarana Meditama Metropolitan T",
    "SAMF": "Saraswanti Anugerah Makmur Tbk",
    "SAPX": "Satria Antaran Prima Tbk.",
    "SATU": "Kota Satu Properti Tbk.",
    "SBMA": "Surya Biru Murni Acetylene Tbk",
    "SCCO": "Supreme Cable Manufacturing &",
    "SCMA": "Surya Citra Media Tbk.",
    "SCNP": "Selaras Citra Nusantara Perkas",
    "SDMU": "Sidomulyo Selaras Tbk.",
    "SDPC": "Millennium Pharmacon Internati",
    "SDRA": "Bank Woori Saudara Indonesia 1",
    "SEMA": "Semacom Integrated Tbk.",
    "SFAN": "Surya Fajar Capital Tbk.",
    "SGER": "Sumber Global Energy Tbk.",
    "SGRO": "Prime Agri Resources Tbk.",
    "SHID": "Hotel Sahid Jaya International",
    "SHIP": "Sillo Maritime Perdana Tbk.",
    "SICO": "Sigma Energy Compressindo Tbk.",
    "SIDO": "Industri Jamu dan Farmasi Sido",
    "SILO": "Siloam International Hospitals",
    "SIMP": "Salim Ivomas Pratama Tbk.",
    "SIPD": "Sreeya Sewu Indonesia Tbk.",
    "SKBM": "Sekar Bumi Tbk.",
    "SKLT": "Sekar Laut Tbk.",
    "SKRN": "Superkrane Mitra Utama Tbk.",
    "SLIS": "Gaya Abadi Sempurna Tbk.",
    "SMAR": "Sinar Mas Agro Resources and T",
    "SMBR": "Semen Baturaja (Persero) Tbk.",
    "SMDM": "Suryamas Dutamakmur Tbk.",
    "SMDR": "Samudera Indonesia  Tbk.",
    "SMGA": "Sumber Mineral Global Abadi Tb",
    "SMGR": "Semen Indonesia (Persero) Tbk.",
    "SMIL": "Sarana Mitra Luas Tbk.",
    "SMKL": "Satyamitra Kemas Lestari Tbk.",
    "SMKM": "Sumber Mas Konstruksi Tbk.",
    "SMLE": "Sinergi Multi Lestarindo Tbk.",
    "SMMA": "Sinarmas Multiartha Tbk.",
    "SMMT": "Golden Eagle Energy Tbk.",
    "SMRA": "Summarecon Agung Tbk.",
    "SMSM": "Selamat Sempurna Tbk.",
    "SNLK": "Sunter Lakeside Hotel Tbk.",
    "SOCI": "Soechi Lines Tbk.",
    "SOFA": "Solusi Environment Asia Tbk.",
    "SOHO": "Soho Global Health Tbk.",
    "SOLA": "Xolare RCR Energy Tbk.",
    "SONA": "Sona Topas Tourism Industry Tb",
    "SOTS": "Satria Mega Kencana Tbk.",
    "SOUL": "Mitra Tirta Buwana Tbk.",
    "SPMA": "Suparma Tbk.",
    "SPRE": "Soraya Berjaya Indonesia Tbk.",
    "SPTO": "Surya Pertiwi Tbk.",
    "SRAJ": "Sejahteraraya Anugrahjaya Tbk.",
    "SRSN": "Indo Acidatama Tbk",
    "SRTG": "Saratoga Investama Sedaya Tbk.",
    "SSIA": "Surya Semesta Internusa Tbk.",
    "SSMS": "Sawit Sumbermas Sarana Tbk.",
    "SSTM": "Sunson Textile Manufacture Tbk",
    "STAA": "Sumber Tani Agung Resources Tb",
    "STAR": "Calculus Global Ventures Tbk.",
    "STRK": "Lovina Beach Brewery Tbk.",
    "STTP": "Siantar Top Tbk.",
    "SULI": "SLJ Global Tbk.",
    "SUNI": "Sunindo Pratama Tbk.",
    "SUPA": "Super Bank Indonesia Tbk.",
    "SURE": "Super Energy Tbk.",
    "SURI": "Maja Agung Latexindo Tbk.",
    "SWID": "Saraswanti Indoland Developmen",
    "TALF": "Tunas Alfin Tbk.",
    "TAPG": "Triputra Agro Persada Tbk.",
    "TAYS": "Jaya Swarasa Agung Tbk.",
    "TBIG": "Tower Bersama Infrastructure T",
    "TBLA": "Tunas Baru Lampung Tbk.",
    "TBMS": "Tembaga Mulia Semanan Tbk.",
    "TCID": "Mandom Indonesia Tbk.",
    "TCPI": "Transcoal Pacific Tbk.",
    "TEBE": "Dana Brata Luhur Tbk.",
    "TFAS": "Telefast Indonesia Tbk.",
    "TGKA": "Tigaraksa Satria Tbk.",
    "TIFA": "KDB Tifa Finance Tbk.",
    "TINS": "Timah Tbk.",
    "TIRA": "Tira Austenite Tbk",
    "TKIM": "Pabrik Kertas Tjiwi Kimia Tbk.",
    "TLDN": "Teladan Prima Agro Tbk.",
    "TLKM": "Telkom Indonesia (Persero) Tbk",
    "TMAS": "Temas Tbk.",
    "TMPO": "Tempo Intimedia Tbk.",
    "TNCA": "Trimuda Nuansa Citra Tbk.",
    "TOBA": "TBS Energi Utama Tbk.",
    "TOOL": "Rohartindo Nusantara Luas Tbk.",
    "TOSK": "Topindo Solusi Komunika Tbk.",
    "TOTL": "Total Bangun Persada Tbk.",
    "TOTO": "Surya Toto Indonesia Tbk.",
    "TOWR": "Sarana Menara Nusantara Tbk.",
    "TPIA": "Chandra Asri Pacific Tbk.",
    "TPMA": "Trans Power Marine Tbk.",
    "TRGU": "Cerestar Indonesia Tbk.",
    "TRIM": "Trimegah Sekuritas Indonesia T",
    "TRIN": "Perintis Triniti Properti Tbk.",
    "TRIS": "Trisula International Tbk.",
    "TRJA": "Transkon Jaya Tbk.",
    "TRON": "Teknologi Karya Digital Nusa T",
    "TRST": "Trias Sentosa Tbk.",
    "TRUE": "Triniti Dinamik Tbk.",
    "TRUK": "Guna Timur Raya Tbk.",
    "TRUS": "Trust Finance Indonesia Tbk",
    "TSPC": "Tempo Scan Pacific Tbk.",
    "TUGU": "Asuransi Tugu Pratama Indonesi",
    "TYRE": "King Tire Indonesia Tbk.",
    "UANG": "Pakuan Tbk.",
    "UCID": "Uni-Charm Indonesia Tbk.",
    "UFOE": "Damai Sejahtera Abadi Tbk.",
    "ULTJ": "Ultrajaya Milk Industry & Trad",
    "UNIC": "Unggul Indah Cahaya Tbk.",
    "UNIQ": "Ulima Nitra Tbk.",
    "UNIT": "Nusantara Inti Corpora Tbk",
    "UNTD": "Terang Dunia Internusa Tbk.",
    "UNTR": "United Tractors Tbk.",
    "UNVR": "Unilever Indonesia Tbk.",
    "URBN": "Urban Jakarta Propertindo Tbk.",
    "UVCR": "Trimegah Karya Pratama Tbk.",
    "VAST": "Vastland Indonesia Tbk.",
    "VERN": "Verona Indah Pictures Tbk.",
    "VICI": "Victoria Care Indonesia Tbk.",
    "VICO": "Victoria Investama Tbk.",
    "VINS": "Victoria Insurance Tbk.",
    "VISI": "Satu Visi Putra Tbk.",
    "VKTR": "VKTR Teknologi Mobilitas Tbk.",
    "VOKS": "Voksel Electric Tbk.",
    "VRNA": "Mizuho Leasing Indonesia Tbk.",
    "VTNY": "Venteny Fortuna International",
    "WAPO": "Wahana Pronatural Tbk.",
    "WBSA": "BSA Logistics Indonesia Tbk.",
    "WEGE": "Wijaya Karya Bangunan Gedung T",
    "WEHA": "WEHA Transportasi Indonesia Tb",
    "WGSH": "Wira Global Solusi Tbk.",
    "WIDI": "Widiant Jaya Krenindo Tbk.",
    "WIFI": "Solusi Sinergi Digital Tbk.",
    "WIIM": "Wismilak Inti Makmur Tbk.",
    "WINE": "Hatten Bali Tbk.",
    "WINS": "Wintermar Offshore Marine Tbk.",
    "WIRG": "WIR ASIA Tbk.",
    "WMUU": "Widodo Makmur Unggas Tbk.",
    "WOMF": "Wahana Ottomitra Multiartha Tb",
    "WOOD": "Integra Indocabinet Tbk.",
    "WOWS": "Ginting Jaya Energi Tbk.",
    "WTON": "Wijaya Karya Beton Tbk.",
    "YELO": "Yelooo Integra Datanet Tbk.",
    "YOII": "Asuransi Digital Bersama Tbk.",
    "YPAS": "Yanaprima Hastapersada Tbk",
    "YULE": "Yulie Sekuritas Indonesia Tbk.",
    "YUPI": "Yupi Indo Jelly Gum Tbk.",
    "ZATA": "Bersama Zatta Jaya Tbk.",
    "ZONE": "Mega Perintis Tbk.",
    "ZYRX": "Zyrexindo Mandiri Buana Tbk.",
    "JKSE": "Index Harga Saham Gabungan",

}
